### ISSUE TITLE
asking help.

### ISSUE THREAD

**Issue by summeroan2** [FCS-analysis/FCSdata#1]
Hello, I want to know is there any method to change the example data format? thank you!

**Comment by paulmueller** [comment]
I am not aware of a data file converter for FCS data. But I am not sure whether that is what you are asking. This is only a data file repository.

**Comment by summeroan2** [comment]
Do you have any avaliable software to process the data? I want to use matlab, but the format unsupported.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Paul Müller"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午3:30
收件人:&nbsp;"FCS-analysis/FCSdata"<FCSdata@noreply.github.com&gt;;
抄送:&nbsp;"Cherophobia"<1574441867@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FCS-analysis/FCSdata] asking help. (#1)





 
I am not aware of a data file converter for FCS data. But I am not sure whether that is what you are asking. This is only a data file repository.

**Comment by paulmueller** [comment]
Yes, these are all example files that can be loaded in PyCorrFit: https://github.com/FCS-analysis/PyCorrFit/releases https://pycorrfit.readthedocs.io/en/stable/

**Comment by summeroan2** [comment]
I am sorry for interrupting，I have no problem with fitting given example FCS data on pyCorrFit, but
I do confused how to processing the data to get the figure below. Can you give me some advice or relevant information regarding processing the obtained data? Thank you very much.




发自我的iPhone


------------------ Original ------------------

**Comment by paulmueller** [comment]
I cannot see any figure. Please have another look at the PyCorrFit documentation. If you are having a problem with PyCorrFit, please create an issue there: https://github.com/FCS-analysis/PyCorrFit/issues
